name: Validate Bicep with PSRule for Azure

on:
  push:
    paths:
      - "**.bicep"
  pull_request:
    paths:
      - "**.bicep"
  workflow_dispatch:  # Allows manual triggering

jobs:
  validate-bicep:
    name: Run PSRule for Azure on Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PowerShell
        run: | 
          # Update the list of packages
          sudo apt-get update
          
          # Install pre-requisite packages.
          sudo apt-get install -y wget apt-transport-https software-properties-common
          
          # Get the version of Ubuntu
          source /etc/os-release
          
          # Download the Microsoft repository keys
          wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
          
          # Register the Microsoft repository keys - Delete the Microsoft repository keys file
          sudo dpkg -i packages-microsoft-prod.deb ; rm packages-microsoft-prod.deb

          # Update the list of packages after we added packages.microsoft.com - Install PowerShell
          sudo apt-get update && sudo apt-get install -y powershell

      - name: Install PSRule for Azure
        run: |
          Install-Module -Name PSRule -Scope CurrentUser -Force -AllowClobber
          Install-Module -Name PSRule.Rules.Azure -Scope CurrentUser -Force -AllowClobber

      - name: Validate Bicep files
        run: |
          Write-Output "Running PSRule validation on Bicep files..."
          Invoke-PSRule -Module 'PSRule.Rules.Azure' -Path . -InputPath '**/*.bicep' -Format Summary
