name: "GitHub Actions - User Driven Parameters"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean

      tags:
        description: 'Test scenario tags'
        required: true
        type: string

      environment:
        description: 'Environment to run tests against'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Placeholder for deployment steps
        run: echo "Deploying to environment: ${{ github.event.inputs.environment }} with log level: ${{ github.event.inputs.logLevel }}"

  print-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.print_tags == 'true' }}
    steps:
      - name: Print the input tags to STDOUT
        run: echo "The tags are ${{ github.event.inputs.tags }}"
