name: Validate Bicep with PSRule for Azure

on:
  push:
    paths:
      - "**.bicep"
  pull_request:
    paths:
      - "**.bicep"
  workflow_dispatch:  # Allows manual triggering

jobs:
  validate-bicep:
    name: Run PSRule for Azure on Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PowerShell
        run: | 
          sudo apt-get update ; sudo apt-get install -y wget apt-transport-https software-properties-common
          source /etc/os-release
          wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb ; rm packages-microsoft-prod.deb
          sudo apt-get update ; sudo apt-get install -y powershell
        shell: bash

      - name: Install Azure Modules for PowerShell
        run: |
          Install-Module -Repository 'PSGallery' -Name 'Az' -Force
        shell: pwsh

      - name: Install PSRule for Azure
        run: |
          Install-Module -Repository 'PSGallery' -Name 'PSRule' -Force
          Install-Module -Repository 'PSGallery' -Name 'PSRule.Rules.Azure' -Force
        shell: pwsh

      - name: Validate Bicep files
        run: |
          Write-Output "Running PSRule validation on Bicep files..."
          Invoke-PSRule -Module 'PSRule.Rules.Azure' -Path . -InputPath '**/*.bicep' -Format Yaml
        shell: pwsh
