name: 'Azure Bicep - Sub Deployment'

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Azure login using Service Principal credentials
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy Bicep file at Tenant level
      - name: Deploy Bicep template at Tenant level
        run: |
          az deployment sub create `
            --location <Region> `
            --template-file ./main.bicep `
            --parameters ./parameters.bicepparam

      # Step 4: Verify deployment (optional)
      - name: Verify deployment
        if: always()
        run: |
          echo "Deployment completed successfully."
