
name: 'Azure OpenID Authentication'
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  id-token: write
  
jobs:
  azure_auth:
    runs-on: ubuntu-latest

    steps:        
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
