name: "Sample Workflow Trigger"

on:
  workflow_dispatch: # Manual trigger from GitHub UI
    inputs:
      environment:
        description: "Target deployment environment"
        required: true
        default: "OVPNSRV01"
        type: choice
        options:
          - OVPNSRV01
          - OVPNSRV02
          - OVPNSRV03     
  push:              
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display trigger info
        run: |
          echo "Workflow triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Selected environment: ${{ inputs.environment || 'N/A' }}"

      - name: Authenticate Azure CLI
        run: |
          echo "Azure Authentication Step"
          sleep 5
          
      - name: "[IaC] - ${{ inputs.environment }} - Deployment"
        run: |
          echo "Deploying IaC to ${{ inputs.environment }}"
          sleep 5
          
